// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "hero": {
    "textType": ["Welcome to my space."],
    "description": "Hi there, My name is Abdulsamad Boudra and I'm Software Developer, Building elegant solutions to complex problems, Passionate about creating beautiful, performant, and user-friendly applications with modern technologies and best practices.",
    "viewMyWorkTitle": "View My Work",
    "getInTouchTitle": "Get in touch"
  },
  "about": {
    "title": "About Me",
    "descriptions": [
      "I'm a passionate software developer with a strong foundation in full-stack development. I love turning ideas into reality through clean, efficient code.",
      "With experience across multiple technologies and frameworks, I specialize in building modern web applications that are both beautiful and functional. I'm constantly learning and staying up-to-date with the latest industry trends",
      "When I'm not coding, you'll find me exploring new technologies, contributing to open-source projects, or sharing knowledge with the developer community."
    ],
    "cards": [
      {
        "icon": "code-xml",
        "title": "Clean Code",
        "description": "Writing maintainable, scalable, and efficient code"
      },
      {
        "icon": "lightbulb",
        "title": "Problem Solver",
        "description": "Create solutions to complex technical challenges"
      },
      {
        "icon": "rocket",
        "title": "Fast Learner",
        "description": "Quick to adapt to new technologies and frameworks"
      },
      {
        "icon": "users",
        "title": "Team Player",
        "description": "Collaborative approach to software development"
      }
    ]
  },
  "skills": {
    "title": "Skills & Technologies",
    "description": "A comprehensive toolkit for building modern, scalable applications. Always exploring new technologies and expanding my skillset",
    "categories": [
      {
        "category": "Frontend",
        "skills": [
          "React",
          "TypeScript",
          "Next.js",
          "Tailwind CSS",
          "Redux",
          "Vue.js"
        ]
      },
      {
        "category": "Backend",
        "skills": ["Node.js", "Express", "PostgreSQL", "MongoDB"]
      },
      {
        "category": "DevOps & Tools",
        "skills": ["Git", "Docker", "AWS", "CI/CD", "Linux", "Kubernetes"]
      },
      {
        "category": "Databases",
        "skills": ["PostgreSQL", "MongoDB"]
      },
      {
        "category": "Other",
        "skills": [
          "REST APIs",
          "GraphQL",
          "Testing",
          "Agile",
          "UI/UX",
          "System Design"
        ]
      },
      {
        "category": "Mobile Apps",
        "skills": ["React Native", "Expo"]
      }
    ]
  },
  "projects": {
    "title": " Featured Projects",
    "description": "Here's what I've been working on recently.",
    "cards": [
      {
        "id": "2",
        "image_url": "/cart.jpg",
        "title": "E-Commerce Platform",
        "description": "A full-featured e-commerce platform with payment integration, inventory management, and admin dashboard. Built with React, Node.js, and PostgreSQL",
        "technologies": ["React", "Node.js", "PostgreSQL", "Stripe", "AWS"],
        "live_url": "",
        "github_url": "",
        "featured": true
      },
      {
        "id": "1",
        "image_url": "/task-management.jpg",
        "title": "Task Management App",
        "description": "Collaborative task management application with real-time updates, team workspaces, and deadline tracking. Features drag-and-drop interface and notifications. ",
        "technologies": ["React", "Firebase", "Tailwind CSS", "Redux"],
        "live_url": "",
        "github_url": "",
        "featured": true
      }
    ],
    "projectsNotFound": {
      "title": "No Projects Found",
      "description": "There are no projects available at this time."
    },
    "liveDemoBtn": "Live demo",
    "githubBtn": "Code"
  },
  "experiences": {
    "title": " Experience & Education",
    "description": "My professional journey and educational background",
    "cards": [
      {
        "type": "work",
        "title": "Full Stack Developer",
        "company": "Freelance",
        "period": "Start - 2014",
        "description": "Delivered high-quality software solutions for diverse clients, transforming ideas into elegant, user-centric applications.",
        "highlights": [
          "Designed and shipped end-to-end applications used by hundreds of clients",
          "Built modular architectures that improved maintainability and scalability",
          "Optimized system performance, reducing load times by up to 45%",
          "Collaborated closely with clients to translate requirements into technical solutions",
          "Maintained long-term relationships through consistent, reliable delivery"
        ]
      },
      {
        "type": "work",
        "title": "Full Stack Developer",
        "company": "Freelance",
        "period": "2025 - Present",
        "description": "Building high-performance, scalable applications and leading core development initiatives across the product lifecycle.",
        "highlights": [
          "Developed and deployed 10+ production-ready applications serving real users",
          "Reduced deployment time by 60% through automated CI/CD pipelines",
          "Implemented performance optimizations resulting in faster response times and improved UX",
          "Contributed to architectural decisions for backend services and frontend workflows",
          "Collaborated with cross-functional teams to deliver features under tight deadlines"
        ]
      }
    ]
  },
  "contact": {
    "title": "Get In Touch",
    "description": "Have a project in mind or want to collaborate? Feel free to reach out! !",
    "directlyEmail": "Or email me directly at",
    "form": {
      "name": { "label": "Your Name", "placeholder": "Enter your name" },
      "email": { "label": "Your Email", "placeholder": "Enter your Email" },
      "content": {
        "label": "Your Message",
        "placeholder": "Enter your message"
      },
      "submitButton": {
        "title": "Send Message",
        "loading": "Sending message..."
      },
      "successMessage": {
        "title": "Message Sent!",
        "message": "Thank you for reaching out. I'll get back to you soon!"
      },
      "errors": {
        "recaptchaRequired": "Please complete the reCAPTCHA verification",
        "recaptchaFailed": "reCAPTCHA verification failed. Please try again.",
        "recaptchaError": "reCAPTCHA verification error. Please try again.",
        "missingFields": "Missing Fields. to Send your message",
        "sendFailed": "Failed to send your message, Please try again.",
        "nameMin": "Name must be at least 1 character",
        "nameMax": "Name must be at most 50 characters",
        "emailInvalid": "Invalid email address",
        "emailMax": "Email must be at most 30 characters",
        "messageMin": "Message must be at least 10 characters",
        "messageMax": "Message must be at most 2000 characters"
      },
      "messages": {
        "success": "Message sent successfully.",
        "successWithEmailFail": "Message sent, but failed to send welcome email."
      }
    }
  },
  "footer": { "title": "Abdulsamad Boudra. Built with passion." },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, en {English} ar {العربية} other {Unknown}}"
  },
  "Layout": {
    "title": "BoudraDev"
  },
  "notFound": {
    "title": "Page Not Found",
    "description": "Sorry, the page you are looking for does not exist.",
    "goHomeButton": "Go Back Home"
  },
    "Manifest": {
    "name": "next-intl example"
  }
};
export default messages;